feat: add missing emojis to sentences that do not have them
codedex-io/github-chapter-2-contributions pull request #285
Opened 2024-10-21 19:22 UTC by CBID2

## Description
There was some sentences that were missing emojis, so I added them

## Issue
Closes #284

2024-10-23 23:44 UTC, intelagense requested changes
This is a fun PR! Although the instructions do say to add emojis to the end, I’m fine with bending the rules a bit to better accommodate a global audience. 

With that in mind, if a line already has an emoticon or emoji anywhere, let's keep it as is since it adds to the charm. If a line has neither, then adding an emoji would be great.

2024-10-23 23:46 UTC, CBID2 commented on README.md
> +Hi, my name is Marcellino Abdelmalak! This was added on 29-06-2024 🌐
```suggestion
Hi, my name is Marcellino Abdelmalak! This was added on 29-06-2024 (〃￣︶￣)人(￣︶￣〃)
```

2024-10-23 23:47 UTC, CBID2 commented on README.md
> +Hi, my name is Fredrik! This was added on 24-03-2024 😎
```suggestion
Hi, my name is Fredrik! This was added on 24-03-2024 :) Swag :)
```

2024-10-23 23:48 UTC, CBID2 commented on README.md
> +Hi, my name is Iamrushabhshahh! This was added on 05-03-2024  💛
```suggestion
Hi, my name is Iamrushabhshahh! This was added on 05-03-2024 ❤️
```

2024-10-23 23:49 UTC, CBID2 commented on README.md
> +Hi, my name is Berkay! This was added on 08.04.2024 🤗
```suggestion
Hi, my name is Berkay! This was added on 08.04.2024 ^-^
```

2024-10-23 23:49 UTC, CBID2 commented on README.md
> +Hi, my name is Sérgio! This was added on 30/05/2024  💛
```suggestion
Hi, my name is Sérgio! This was added on 30/05/2024  :)
```

2024-10-23 23:50 UTC, CBID2 commented on README.md
> +Hi, my name is Lenny! This was added on 29-06-24 🌙
```suggestion
Hi, my name is Lenny! This was added on 29-06-24 :)
```

2024-10-23 23:50 UTC, CBID2 commented on README.md
> +Hey, Kshitij Akarsh was here on 01-06-2024. 💖
```suggestion
Hey, Kshitij Akarsh was here on 01-06-2024. :)
```

2024-10-23 23:51 UTC, CBID2 reviewed
Add these changes

2024-10-23 23:52 UTC, CBID2 commented
> This is a fun PR! Although the instructions do say to add emojis to the end, I’m fine with bending the rules a bit to better accommodate a global audience.
> 
> With that in mind, if a line already has an emoticon or emoji anywhere, let's keep it as is since it adds to the charm. If a line has neither, then adding an emoji would be great.

Hi @intelagense! :) I made the changes

2024-10-24 01:20 UTC, CBID2 commented
Made the changes @intelagense

2024-10-29 16:01 UTC, intelagense commented
I don't if I am looking at it wrong but I still see a few like ":)"s and "XD"s that have been altered in the PR. 🙏

2024-10-29 17:09 UTC, CBID2 reviewed
Make those changes

2024-10-29 17:09 UTC, CBID2 commented on README.md
> +Hi, my name is Xilient! This was added on <19-03-2024> 😎
```suggestion
Hi, my name is Xilient! This was added on <19-03-2024> <:D>
```

2024-10-29 17:09 UTC, CBID2 commented on README.md
> +HI! Jair Robles was Here🐨, 14th Oct 2024.  💛
```suggestion
HI! Jair Robles was Here🐨, 14th Oct 2024.  
```

2024-10-29 17:09 UTC, CBID2 commented on README.md
> +Hi, my name is Estarth! This was added on 11/06/2024 🍒
```suggestion
Hi, my name is Estarth! This was added on 11/06/2024 XD
```

2024-10-29 17:12 UTC, CBID2 commented
> I don't if I am looking at it wrong but I still see a few like ":)"s and "XD"s that have been altered in the PR. 🙏 

Hey @intelagense! 😁 You're right. There were a few ":)"s and "XD"s that have been altered. I corrected them

2024-10-29 22:16 UTC, intelagense approved these changes

2024-10-29 22:18 UTC, intelagense commented
I added this one back in and left the heart as well. "^\_^" I think it's maybe a kaomoji with a scar but I have no idea. 🤷 

Thanks for the PR!

2024-10-29 22:19 UTC, merged

2024-10-29 22:21 UTC, intelagense commented
Ah the slash was the escape for the underscore in markdown. 👍